### ISSUE TITLE
挺牛逼的！

### ISSUE THREAD

**Issue by moushao** [forJrking/HeiPermission#2]
楼主，你这库挺牛逼的！！！但是有两个问题！
第一：封装在Activity中，一般来说我们都有自己的baseAC！
第二（这个并不是你的问题，是谷孙的）：fragment中的调用方式不一致，楼主用object强制回调到Activity中，再回调到Fragment，但是，如果Fragment再嵌套Fragment就洗白了，getParent都没用！！！而且如果fragment是new的，不是通过fragmentManager加载 的，洗白了！洗白的意思是，请求后没回调！！！我开始以为是楼主的问题，后来才发现不是！！
废话一大堆，总结就是！！！这封装还是蛮牛逼的！值得使用！！！

**Comment by forJrking** [comment]
不客气，技术有点老旧。但是思路不够，考虑AOP用注解任何地方可实现
